### ISSUE TITLE
Problem with Ubuntu 18.04 LTS - First start

### ISSUE THREAD

**Issue by DieSteinhose** [ajenti/ajenti#1241]
Hey, i got this mesage on my test server, fresh Ubuntu install. I have tried to downgrade gevent to version 1.3.7 before #1232 

Ajenti bug report
--------------------

Info | Value
----- | -----
Ajenti | 2.1.33
Platform | debian / ubuntu / Ubuntu 18.04.4 LTS
Architecture | x86_64 x86_64
Python | 2.7.17
Debug | True
Loaded plugins |

Library | Version
------- | -------
gevent | 1.3.7
greenlet | 0.4.15
psutil | 5.7.0

    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/aj/entry.py", line 52, in handle_crash
        report = open(report_path, 'w')
    IOError: [Errno 13] Permission denied: '/root/ajenti-crash.txt'

via "ajenti-panel -v" i got this

```
24.04.2020 17:51  [...     2371]  DEBUG    Registering [aj.api.http.HttpMiddleware] (interface)
24.04.2020 17:51  [...     2371]  DEBUG    Registering [aj.api.http.HttpPlugin] (interface)
24.04.2020 17:51  [...     2371]  DEBUG    Registering [aj.api.http.SocketEndpoint] (interface)
24.04.2020 17:51  [...     2371]  DEBUG    Registering [aj.security.verifier.ClientCertificateVerificator] (service)
24.04.2020 17:51  [...     2371]  DEBUG    Registering [aj.auth.AuthenticationMiddleware] (service)
24.04.2020 17:51  [...     2371]  DEBUG    Registering [aj.auth.AuthenticationProvider] (interface)
24.04.2020 17:51  [...     2371]  DEBUG    Registering [aj.auth.OSAuthenticationProvider] (implementation of [aj.auth.AuthenticationProvider])
24.04.2020 17:51  [...     2371]  DEBUG    Registering [aj.auth.AuthenticationService] (service)
24.04.2020 17:51  [...     2371]  DEBUG    Registering [aj.auth.PermissionProvider] (interface)
24.04.2020 17:51  [...     2371]  DEBUG    Registering [aj.routing.CentralDispatcher] (service)
24.04.2020 17:51  [...     2371]  DEBUG    Registering [aj.gate.middleware.SocketIORouteHandler] (service)
24.04.2020 17:51  [...     2371]  DEBUG    Registering [aj.gate.middleware.GateMiddleware] (service)
24.04.2020 17:51  [...     2371]        compat.py:19    DEBUG    Popen: ['lsb_release', '-sd']
24.04.2020 17:51  [master  2371]          core.py:71    INFO   Loading config from /etc/ajenti/config.yml
24.04.2020 17:51  [master  2371]         entry.py:47    ERROR  Fatal crash occured
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aj/entry.py", line 37, in start
    aj.core.run(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/aj/core.py", line 72, in run
    aj.config.load()
  File "/usr/local/bin/ajenti-panel", line 30, in load
    self.data = yaml.load(open(self.path), Loader=yaml.Loader)
IOError: [Errno 13] Permission denied: '/etc/ajenti/config.yml'
24.04.2020 17:51  [master  2371]        compat.py:19    DEBUG  Popen: ['uname', '-mp']
24.04.2020 17:51  [master  2371]         entry.py:60    ERROR  Crash report written to ./ajenti-crash.txt

```

thanks in advance

**Comment by kiarn** [comment]
Hello @Logimann 

I would check the permission of the file `/etc/ajenti/config.yml`, your problem is not related to gevent.

**Comment by DieSteinhose** [comment]
Hey @kiarn 

Thanks, now I have the next problem. Now I get the error "Could not bind: [Errno 98] The address is already in use.
I also changed the port, without any effect. Firewall ufw is disabled.

Should I create a new issue for this?

**Comment by kiarn** [comment]
No, I don't think this is an issue, I think Ajenti was still working as you restarted it.
Check what `ps aux | grep aj`, try to kill the ajenti process and to properly restart it.

**Comment by DieSteinhose** [comment]
I kill the ajenti process and restarted it with "service ajenti restat". 

It's not working yet. I'm using this to test my locale vm and try to open the file with the firefox browser in the vm via localhost:8000

**Comment by kiarn** [comment]
What's the output of : 

`systemctl status ajenti`

What's the content of `/etc/ajenti.config.yml` ? Is the port set to 8000 ?

**Comment by DieSteinhose** [comment]
systemctl status ajenti:
```
● ajenti.service - Ajenti panel
   Loaded: loaded (/lib/systemd/system/ajenti.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2020-04-25 10:49:39 PDT; 3h 49min ago
  Process: 11004 ExecStart=/usr/bin/python /usr/local/bin/ajenti-panel -d (code=exited, status=0/SUCCESS)
 Main PID: 11006 (/usr/bin/python)
    Tasks: 2 (limit: 9464)
   CGroup: /system.slice/ajenti.service
           ├─11006 /usr/bin/python /usr/local/bin/ajenti-panel -d
           └─11011 /usr/local/bin/ajenti-panel worker [restricted session]

Apr 25 10:49:39 ubuntu systemd[1]: Starting Ajenti panel...
Apr 25 10:49:39 ubuntu systemd[1]: ajenti.service: Can't open PID file /var/run/ajenti.pid (yet?) after start: No such file or directory
Apr 25 10:49:39 ubuntu systemd[1]: Started Ajenti panel.

```

content of config.yml


```
auth:
  allow_sudo: true
  emails: {}
  provider: os
bind:
  host: 0.0.0.0
  mode: tcp
  port: 8000
color: default
max_sessions: 9
session_max_time: 3600
name: ubuntu
ssl:
  certificate:
  fqdn_certificate:
  client_auth:
    certificates: []
    enable: false
    force: false
  enable: false

```

**Comment by kiarn** [comment]
I have maybe an idea, try : 

`systemctl stop ajenti`

and then : 

`/usr/bin/python3 /usr/local/bin/ajenti-panel -d`

If it not works, maybe there's some error in `/var/log/ajenti/ajenti.log` ?

**Comment by DieSteinhose** [comment]
When I type `/usr/bin/python3 /usr/local/bin/ajenti-panel -d` this in this message appears.
```
Traceback (most recent call last):
  File "/usr/local/bin/ajenti-panel", line 10, in <module>
    import aj
ModuleNotFoundError: No module named 'aj'
```
i have also tried a old python  `/usr/bin/python /usr/local/bin/ajenti-panel -d` It seems to have done something.

Interestingly, it worked for a short time, after I downgraded gevent to 1.3.7 again. But after a reboot I'm back to the `cloud not bind` problem. Even after I went through all the steps again. I do not understand this.

Here is the part of the log
```
2020-04-25 16:49:56,298 INFO    : Loaded 11 plugins
2020-04-25 16:49:56,299 INFO    : Binding to [0.0.0.0]:8000
2020-04-25 16:49:56,303 ERROR   : Fatal crash occured
2020-04-25 16:49:56,308 INFO    : New worker "restricted session" PID 3551, EUID 0, EGID 0
2020-04-25 16:49:56,309 INFO    : Worker 3551 is demoting to UID 65534 / GID 65534...
2020-04-25 16:49:56,309 INFO    : ...done, new EUID 65534 EGID 65534
2020-04-25 16:49:56,310 ERROR   : Crash report written to /root/ajenti-crash.txt
```

ajenti-crash.txt:

```
Ajenti bug report
--------------------


Info | Value
----- | -----
Ajenti | 2.1.33
Platform | debian / ubuntu / Ubuntu 18.04.4 LTS
Architecture | x86_64 x86_64
Python | 2.7.17
Debug | False
Loaded plugins | ace, core, dashboard, filemanager, filesystem, notepad, packages, passwd, services, settings, terminal

Library | Version
------- | -------
gevent | 20.04.0
greenlet | 0.4.15
psutil | 5.7.0


    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/aj/entry.py", line 30, in start
        aj.core.run(**kwargs)
      File "/usr/local/lib/python2.7/dist-packages/aj/core.py", line 208, in run
        gevent.signal(signal.SIGINT, signal_handler)
    TypeError: 'module' object is not callable

```

I don't know why it says Gevent 20.04.0

**Comment by kiarn** [comment]
Ajenti 2.1.34 will only work with `Python3` and `gevent 1.3.7`, but the `install.sh`, `systemctl` file, etc ... are not up to date in this repo. 

So I would suggest to begin the install again, I made tests with a 18.04 fresh install, and this should hopefully work (as root): 

```
add-apt-repository universe
apt update
apt-get install -y build-essential python3-pip python3-dev python3-lxml libffi-dev libssl-dev libjpeg-dev libpng-dev uuid-dev python3-dbus python3-augeas python3-apt ntpdate
python3 -m pip install -U pip wheel setuptools
python3 -m pip uninstall -y gevent-socketio gevent-socketio-hartwork
python3 -m pip install ajenti-panel ajenti.plugin.core ajenti.plugin.dashboard ajenti.plugin.settings ajenti.plugin.plugins ajenti.plugin.notepad ajenti.plugin.terminal ajenti.plugin.filemanager ajenti.plugin.packages ajenti.plugin.services
python3 -m pip install gevent==1.3.7 pyte==0.8.0
```

After that, you don't have any `sysini` or `systemctl` file to start/restart/stop ajenti, but only the base to test it, then try again : 

`/usr/bin/python3 /usr/local/bin/ajenti-panel -d`

If this works, we have a good startpoint and then we can go further. I will as soon as possible update `install.sh` and the documentation.

**Comment by count00zero** [comment]
I tried that (on Ubuntu 20.04) and had to face the following:
`AttributeError: module 'platform' has no attribute 'linux_distribution'`

**Comment by kiarn** [comment]
Ubuntu 20.04 comes with Python3.7 and some deprecated functions are not usable anymore.
I'm currently testing/correcting for Bionic/centos 8/debian 9.

> I tried that (on Ubuntu 20.04) and had to face the following:
> `AttributeError: module 'platform' has no attribute 'linux_distribution'`

I corrected this specific issue for the next version : https://github.com/kiarn/ajenti/commit/7587c6ecf731bb0f812774b025dbe3b216d087a9

**Comment by count00zero** [comment]
thanks a lot!

**Comment by kiarn** [comment]
Ajenti 2.1.35 is out, and I was able to install it via automated script on a fresh Ubuntu 20.04, please try it.

**Comment by count00zero** [comment]
Hi and thanks for the information.
Install works great, but when I start it: 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aj/entry.py", line 40, in start
    aj.core.run(dev_mode=dev_mode, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/aj/core.py", line 99, in run
    if aj.config.data['bind']['mode'] == 'unix':
KeyError: 'mode'
```

Has the config.yml the same content as the old .json?
Or is there a difference?

**Comment by kiarn** [comment]
Hi,

You have a sample config file for ajenti 2 here : https://github.com/ajenti/ajenti/blob/master/ajenti-panel/config.yml

**Comment by count00zero** [comment]
Thanks, that did the trick!
Ajenti 2 running now on Ubuntu 20.04-
Another Question: will Ajenti 1.x (which I like because of the "richness" someday run on python3?

**Comment by RaykDev01** [comment]
Hello: I try to login after the Instalation of Ajenti 2 in Ubuntu 18 and I put the root in user and my admin password in the password and said authentication failed. Why?

**Comment by kiarn** [comment]
Hello,

I just made an automatic install (see : http://docs.ajenti.org/en/latest/man/install.html#automatic-installation ) on a fresh Ubuntu 18.04 server, and I cannot reproduce this. Do you have some error in `/var/log/ajenti/ajenti.log` ?

Regards

Arnaud
